### ISSUE TITLE
False Positive - Repeated Pause

### ISSUE THREAD

**Issue by thewishy** [nberktumer/ha-bambu-lab-p1-spaghetti-detection#17]
I've found that the tool deployed quickly and works pretty well and has certainly saved my some wasted filament. 

Some models create more false positives than others, for example the first layers of this https://www.printables.com/model/490570-fairy-tree-ring-and-jewelry-holder understandably caused continuous false positives for the first few layers. 

I found that when I selected result, it would very quickly pause again as the algorithm still flagged the design as string. 

Perhaps as a quality of life feature, it could pause on the first detection, but further pauses could be suspended for a few layers?
I've added a script to turn off the automation for a few layers, but thought I'd raise it as a nice little RFE

Thanks for your hard work here

**Comment by btastic** [comment]
I noticed that too.

The problem is that the P value is never going down during pausing, since the automation is only updating P when the status is printing.

So it detects at 0.8 P and it will trigger the pause. You quickly fix it and hit resume. Since you were quick, the nozzle is not taking much time to heat up, so the P is not going down quick enough. Then P will retrigger at 0.5, since it only dropped down to 0.5.

My suggestion would be to reset the calculated values once a detection happened, or to keep the calculation running during idle (which seems to be not ideal imo)

**Comment by btastic** [comment]
I created a PR which can resolve the issue: #19
