### ISSUE TITLE
How to get it to work with SSL enabled on Home Assistant?

### ISSUE THREAD

**Issue by LondonPaul** [nberktumer/ha-bambu-lab-p1-spaghetti-detection#38]
Any guidance on how to get this working if my HA instance is set up to access using ssl? I have my own domain name, nginx server which redirects to HA which is running on HAOS / Proxmox and has cert installed. I’m using the Home Assistant addon for Obico. If I put in the IP address it complains that the SSL name doesn’t match, if I put in the domain name it doesn’t resolve?

**Comment by nberktumer** [comment]
I have a setup with Ubuntu Host with many docker containers and all the containers can resolve my domains. I suppose this is a DNS issue since your HAOS instance cannot resolve your domain. What is the DNS on your HAOS instance? If your domain is not public, you may need to change your DNS on HAOS with a DNS server, which can resolve your domain.

**Comment by LondonPaul** [comment]
Thanks for your comment. Sent me in the right direction and made me realise it was an issue with my nginx configuration. Working now!
